# Generated by Django 3.2.4 on 2021-09-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='patient_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
