# Generated by Django 3.2.4 on 2021-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatdata_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdata',
            name='doctor_user',
        ),
        migrations.AddField(
            model_name='chatdata',
            name='doctor_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
