# Generated by Django 3.2.4 on 2021-09-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210904_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdata',
            old_name='patient_id',
            new_name='chat_id',
        ),
        migrations.RemoveField(
            model_name='chatdata',
            name='doctor_id',
        ),
    ]
