# Generated by Django 3.2.4 on 2021-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210904_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='patient_name',
            field=models.CharField(default='n/a', max_length=250),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='chat_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='chat_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
