# Generated by Django 3.2.4 on 2021-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionType',
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
