# Generated by Django 3.2.4 on 2021-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210622_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SingleChoice', 'בחירה יחידה'), ('MultipleChoice', 'בחירה מרובה'), ('OpenQuestion', 'שאלה פתוחה')], default='OpenQuestion', max_length=20),
        ),
    ]
