# Generated by Django 3.2.4 on 2021-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Single_Choice', 'בחירה יחידה'), ('Multiple_Choice', 'בחירה מרובה'), ('Open_Question', 'שאלה פתוחה')], default='OpenQuestion', max_length=20),
        ),
    ]
