# Generated by Django 3.2.4 on 2021-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SingleChoice', 'בחירה יחידה'), ('MultipleChoice', 'בחירה מרובה'), ('OpenQuestion', 'שאלה פתוחה')], default='OpenQuestion', max_length=20),
        ),
    ]
