# Generated by Django 3.2.4 on 2021-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questionnaire_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
