# Generated by Django 3.2.4 on 2021-08-06 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 8, 6)),
        ),
    ]
