# Generated by Django 3.2.4 on 2021-09-07 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patient_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.EmailField(default='n/a', max_length=255)),
                ('action_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
