# Generated by Django 3.2.4 on 2021-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medicalaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalaction',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
