# Generated by Django 3.2.4 on 2021-09-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medicalaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaction',
            name='action',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
